routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' =>['auth']], function(){
	Route::get('/home', 'HomeController@index')->name('home');
	
	Route::prefix('admin')->middleware('isAdmin')->name('admin.')->group(function() {
		Route::resource('/task', 'admin\TaskController');
		Route::resource('/staff', 'admin\UserController');
	});

	Route::prefix('staff')->middleware('isStaff')->group(function() {
		Route::get('/task', 'staff\TaskController@index')->name('staff.task.index');
		Route::get('/task/{id}', 'staff\TaskController@show')->name('staff.task.show');
		Route::get('/task/{id}/accept', 'staff\TaskController@accept')->name('staff.task.accept');
		Route::get('/task/{id}/complete', 'staff\TaskController@complete')->name('staff.task.complete');
	});
});

app/Http/Controllers/admin/TaskController.php
<?php

namespace App\Http\Controllers\admin;

use Auth;
use App\Model\Task;
use App\Model\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Notifications\TaskAssigned;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::orderBy('created_at', 'desc')->paginate(50);
        return view('admin.task.index',compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $staffs = User::where('role','staff')->orderBy('name', 'asc')->get();
        return view('admin.task.create', compact('staffs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'staff_id' => 'required',
            'title' => 'required',
            'description' => 'required',
            'deadline' => 'required',
            'remarks' => 'sometimes',
        ]);
        $data = [
            'task_from' => Auth::user()->id,
            'task_to' => $request->staff_id,
            'title' => $request->title,
            'description' => $request->description,
            'accept_status' => 0,
            'status' => 'unaccept',
            'deadline' => $request->deadline,
            'remarks' => $request->remarks,
        ];
        $task = Task::create($data);
        $staff = User::find($request->staff_id);
        $staff->notify(new TaskAssigned($task));
        return redirect()->route('admin.task.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::find($id);
        foreach(auth()->user()->unreadNotifications as $notification){
            if($id == $notification->data['task_id']){
                Auth::user()->unreadNotifications->where('id', $notification->id)->markAsRead();
            }
        }
        return view('admin/task/view', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find($id);
        $staffs = User::where('role','staff')->orderBy('name', 'asc')->get();
        return view('admin.task.edit', compact('task', 'staffs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'staff_id' => 'required',
            'title' => 'required',
            'description' => 'required',
            'deadline' => 'required',
            'remarks' => 'sometimes',
        ]);
        $data = [
            'task_from' => Auth::user()->id,
            'task_to' => $request->staff_id,
            'title' => $request->title,
            'description' => $request->description,
            'accept_status' => 0,
            'status' => 'unaccept',
            'deadline' => $request->deadline,
            'remarks' => $request->remarks,
        ];
        Task::find($id)->update($data);
        return redirect()->route('admin.task.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Task::find($id)->delete();
        return redirect()->route('admin.task.index');
    }
}

app/Http/Controllers/staff/TaskController.php
<?php

namespace App\Http\Controllers\staff;

use Auth;
use App\Model\Task;
use App\Model\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Notifications\TaskCompleted;
use App\Notifications\TaskAccepted;

class TaskController extends Controller
{
    public function index()
    {
    	$tasks = Task::where('task_to', Auth::user()->id)->paginate(10);
    	return view('staff.task.index', compact('tasks'));
    }
    public function show($id)
    {
        $task = Task::find($id);
        foreach(auth()->user()->unreadNotifications as $notification){
            if($id == $notification->data['task_id']){
                Auth::user()->unreadNotifications->where('id', $notification->id)->markAsRead();
            }
        }
        return view('staff/task/view', compact('task'));
    }
    public function accept($id)
    {
    	Task::find($id)->update(['accept_status' => 1, 'status' => 'onprocess']);
        $task = Task::find($id);
        $staff = User::find($task->task_from);
        $staff->notify(new TaskAccepted($task));
    	return redirect()->back();
    }
    public function complete($id)
    {
    	$date = Carbon::now()->format('Y-m-d');
    	Task::find($id)->update(['completed_date' => $date, 'status' => 'complete']);
        $task = Task::find($id);
        $staff = User::find($task->task_from);
        $staff->notify(new TaskCompleted($task));
    	return redirect()->back();
    }
}

resources/views/admin/task/create.blade.php
@extends('layouts.app')

@section('content')
<link rel="stylesheet"
  href="{{asset('adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="box">
                        <div class="box-title">
                            <h3>Create Staffs</h3>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form action="{{route('admin.task.store')}}" class="form-horizontal" method="post">
                                        {!! csrf_field() !!}
                                        <div class="form-group">
                                            <label class="col-md-2">Title</label>
                                            <div class="col-md-10">
                                                <input type="text" name="title" class="form-control" placeholder="title">
                                                @if ($errors->has('title'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('title') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Select Staff</label>
                                            <div class="col-md-10">
                                                <select name="staff_id" id="staff_id" class="form-control">
                                                    <option value="">Select Staff</option>
                                                    @foreach($staffs as $staff)
                                                    <option value="{{$staff->id}}">{{$staff->name}}</option>
                                                    @endforeach
                                                </select>
                                                @if ($errors->has('staff_id'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('staff_id') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Description</label>
                                            <div class="col-md-10">
                                                <textarea name="description" class="form-control" placeholder="description"></textarea>
                                                @if ($errors->has('description'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('description') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Deadline</label>
                                            <div class="col-md-10">
                                                <input type="text" name="deadline" id="deadline" value="{{date('Y-m-d')}}" class="form-control">
                                                @if ($errors->has('deadline'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('deadline') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Remarks</label>
                                            <div class="col-md-10">
                                                <input type="text" name="remarks" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2"></label>
                                            <div class="col-md-10">
                                                <input type="submit" class="btn btn-sm btn-primary" value="Submit">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{asset('adminlte/bower_components/jquery/dist/jquery.min.js')}}"></script>
<script src="{{asset('adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
<script>
    $('#deadline').datepicker({
        autoclose: true,
        format: 'yyyy-m-d',
        startDate: '-0d'
      })
</script> 
@endsection

resources/views/admin/task/edit.blade.php
@extends('layouts.app')

@section('content')
<link rel="stylesheet"
  href="{{asset('adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="box">
                        <div class="box-title">
                            <h3>Create Staffs</h3>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form action="{{route('admin.task.update', $task->id)}}" class="form-horizontal" method="post">
                                        {!! csrf_field() !!}
                                        {!! method_field('PUT') !!}
                                        <div class="form-group">
                                            <label class="col-md-2">Title</label>
                                            <div class="col-md-10">
                                                <input type="text" name="title" class="form-control" placeholder="title" value="{{$task->title}}">
                                                @if ($errors->has('title'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('title') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Select Staff</label>
                                            <div class="col-md-10">
                                                <select name="staff_id" id="staff_id" class="form-control">
                                                    <option value="">Select Staff</option>
                                                    @foreach($staffs as $staff)
                                                    <option value="{{$staff->id}}" @if($staff->id == $task->task_to) selected @endif>{{$staff->name}}</option>
                                                    @endforeach
                                                </select>
                                                @if ($errors->has('staff_id'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('staff_id') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Description</label>
                                            <div class="col-md-10">
                                                <textarea name="description" class="form-control" placeholder="description">{{$task->description}}</textarea>
                                                @if ($errors->has('description'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('description') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Deadline</label>
                                            <div class="col-md-10">
                                                <input type="text" name="deadline" id="deadline" value="{{$task->deadline}}" class="form-control" >
                                                @if ($errors->has('deadline'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('deadline') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Remarks</label>
                                            <div class="col-md-10">
                                                <input type="text" name="remarks" class="form-control" value="{{$task->remarks}}">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2"></label>
                                            <div class="col-md-10">
                                                <input type="submit" class="btn btn-sm btn-primary" value="Submit">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{asset('adminlte/bower_components/jquery/dist/jquery.min.js')}}"></script>
<script src="{{asset('adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
<script>
    $('#deadline').datepicker({
        autoclose: true,
        format: 'yyyy-m-d',
        startDate: '-0d'
      })
</script> 
@endsection

resources/views/admin/task/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="box">
                        <div class="box-title">
                            <h3>Staffs</h3>
                            <a href="{{route('admin.task.create')}}" class="btn btn-sm btn-primary pull-right">CREATE</a>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-bordered">
                                        <tr>
                                            <th>SN</th>
                                            <th>Title</th>
                                            <th>Assigned To</th>
                                            <th>Status</th>
                                            <th>Deadline</th>
                                            <th>Action</th>
                                        </tr>
                                        @foreach($tasks as $k=>$task)
                                        <tr>
                                            <td>{{$k+1}}</td>
                                            <td>{{$task->title}}</td>
                                            <td>{{\App\Model\User::getName($task->task_to)}}</td>
                                            <td>
                                                @if($task->status=='unaccept')
                                                <label class="label bg-yellow">{{$task->status}}</label>
                                                @elseif($task->status=='onprocess')
                                                <label class="label bg-blue">{{$task->status}}</label>
                                                @elseif($task->status=='complete')
                                                <label class="label bg-green">{{$task->status}}</label>
                                                @else
                                                <label class="label bg-red">{{$task->status}}</label>
                                                @endif
                                            </td>
                                            <td>{{\Carbon\Carbon::parse($task->deadline)->format('d M, Y')}}</td>
                                            <td>
                                                <form action="{{route('admin.task.destroy', $task->id)}}" method="post">
                                                {!! csrf_field() !!}
                                                {!! method_field('DELETE') !!}  
                                                <a href="{{route('admin.task.show', $task->id)}}" class="btn btn-sm btn-success">VIEW</a> 
                                                @if($task->status != 'complete')
                                                <a href="{{route('admin.task.edit', $task->id)}}" class="btn btn-sm btn-info">EDIT</a> 
                                                @endif
                                                <button type="submit" class="btn btn-sm btn-danger">DELEET</button>
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </table>
                                    <div class="text-center">{{$tasks->links()}}</div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/task/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="box">
                        <div class="box-title">
                            <h3>Task View</h3>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-bordered">
                                    	<tr>
                                    		<td>Title</td>
                                    		<td>{{$task->title}}</td>
                                    	</tr>
                                    	<tr>
                                    		<td>Task Assigned By</td>
                                    		<td>{{\App\Model\User::getName($task->task_from)}}</td>
                                    	</tr>
                                    	<tr>
                                    		<td>Task Assigned To</td>
                                    		<td>{{\App\Model\User::getName($task->task_to)}}</td>
                                    	</tr>
                                    	<tr>
                                    		<td>Description</td>
                                    		<td>{{$task->description}}</td>
                                    	</tr>
                                    	<tr>
                                    		<td>Status</td>
                                    		<td>{{$task->status}}</td>
                                    	</tr>
                                    	<tr>
                                    		<td>Deadline</td>
                                    		<td>{{\Carbon\Carbon::parse($task->deadline)->format('d M, Y')}}</td>
                                    	</tr>
                                    	<tr>
                                    		<td>Completion Date</td>
                                    		<td>
                                    			@if($task->completed_date)
                                    			{{\Carbon\Carbon::parse($task->completed_date)->format('d M, Y')}}
                                    			@endif
                                    		</td>
                                    	</tr>
                                        <tr>
                                            <td>Remarks</td>
                                            <td>{{$task->remarks}}</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection