routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' =>['auth']], function(){
	Route::get('/home', 'HomeController@index')->name('home');
	
	Route::prefix('admin')->middleware('isAdmin')->name('admin.')->group(function() {
		Route::resource('/task', 'admin\TaskController');
		Route::resource('/staff', 'admin\UserController');
	});

	Route::prefix('staff')->middleware('isStaff')->group(function() {
		Route::get('/task', 'staff\TaskController@index')->name('staff.task.index');
		Route::get('/task/{id}', 'staff\TaskController@show')->name('staff.task.show');
		Route::get('/task/{id}/accept', 'staff\TaskController@accept')->name('staff.task.accept');
		Route::get('/task/{id}/complete', 'staff\TaskController@complete')->name('staff.task.complete');
	});
});

app/Http/Controllers/admin/UserController.php
<?php

namespace App\Http\Controllers\admin;

use App\Model\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function index()
    {
        $staffs = User::where('id', '!=', 1)->orderBy('id', 'desc')->paginate(50);
        return view('admin/user/index', compact('staffs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/user/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required',
            'password' => 'required',
            'role' => 'required'
        ]);
        $data = [
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'role' => $request->role,
        ];
        User::create($data);
        return redirect()->route('admin.staff.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $staff = User::find($id);
        return view('admin/user/edit', compact('staff'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required',
            'password' => 'required',
            'role' => 'required'
        ]);
        if($request->password){
            $data['password'] = Hash::make($request->password);
        }
        $data = [
            'name' => $request->name,
            'email' => $request->email,
            'role' => $request->role,
        ];
        User::find($id)->update($data);
        return redirect()->route('admin.staff.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('admin.staff.index');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="box">
                        <div class="box-title">
                            <h3>Create Staffs</h3>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form action="{{route('admin.staff.store')}}" class="form-horizontal" method="post">
                                        {!! csrf_field() !!}
                                        <div class="form-group">
                                            <label class="col-md-2">Name</label>
                                            <div class="col-md-10">
                                                <input type="text" name="name" class="form-control" placeholder="name">
                                                @if ($errors->has('name'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('name') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Email</label>
                                            <div class="col-md-10">
                                                <input type="email" name="email" class="form-control" placeholder="xyz@mail.com">
                                                @if ($errors->has('email'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('email') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Password</label>
                                            <div class="col-md-10">
                                                <input type="password" name="password" class="form-control" placeholder="password">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Role</label>
                                            <div class="col-md-10">
                                                <select name="role" id="role" class="form-control">
                                                    <option value="">Select Role</option>
                                                    <option value="admin">Admin</option>
                                                    <option value="staff">Staff</option>
                                                </select>
                                                @if ($errors->has('role'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('role') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2"></label>
                                            <div class="col-md-10">
                                                <input type="submit" class="btn btn-sm btn-primary" value="Submit">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="box">
                        <div class="box-title">
                            <h3>Create Staffs</h3>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form action="{{route('admin.staff.update', $staff->id)}}" class="form-horizontal" method="post">
                                        {!! csrf_field() !!}
                                        {!! method_field('PUT') !!}
                                        <div class="form-group">
                                            <label class="col-md-2">Name</label>
                                            <div class="col-md-10">
                                                <input type="text" name="name" class="form-control" placeholder="name" value="{{$staff->name}}">
                                                @if ($errors->has('name'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('name') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Email</label>
                                            <div class="col-md-10">
                                                <input type="email" name="email" class="form-control" placeholder="xyz@mail.com" value="{{$staff->email}}">
                                                @if ($errors->has('email'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('email') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Password</label>
                                            <div class="col-md-10">
                                                <input type="password" name="password" class="form-control" placeholder="password" autocomplete="off">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2">Role</label>
                                            <div class="col-md-10">
                                                <select name="role" id="role" class="form-control">
                                                    <option value="">Select Role</option>
                                                    <option value="admin" @if($staff->role=='admin') selected @endif>Admin</option>
                                                    <option value="staff" @if($staff->role=='staff') selected @endif>Staff</option>
                                                </select>
                                                @if ($errors->has('role'))
                                                    <span class="text-danger">
                                                        {{ $errors->first('role') }}
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2"></label>
                                            <div class="col-md-10">
                                                <input type="submit" class="btn btn-sm btn-primary" value="Submit">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="box">
                        <div class="box-title">
                            <h3>Staffs</h3>
                            <a href="{{route('admin.staff.create')}}" class="btn btn-sm btn-primary pull-right">CREATE</a>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-bordered">
                                        <tr>
                                            <th>SN</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Role</th>
                                            <th>Action</th>
                                        </tr>
                                        @foreach($staffs as $k=>$staff)
                                        <tr>
                                            <td>{{$k+1}}</td>
                                            <td>{{$staff->name}}</td>
                                            <td>{{$staff->email}}</td>
                                            <td>{{$staff->role}}</td>
                                            <td>
                                                <form action="{{route('admin.staff.destroy', $staff->id)}}" method="post">
                                                {!! csrf_field() !!}
                                                {!! method_field('DELETE') !!}  
                                                <a href="{{route('admin.staff.edit', $staff->id)}}" class="btn btn-sm btn-info">EDIT</a> 
                                                <button type="submit" class="btn btn-sm btn-danger">DELEET</button>
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </table>
                                    <div class="text-center">{{$staffs->links()}}</div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection